### PR TITLE
Update with streamlined config

### PR DESCRIPTION
**Pull request by karlomikus**

### CODE REVIEW

**Comment by MathieuMoalic** [comment]
Hi, Having `API_URL=$BASE_URL/bar` in the .env does not resolve to the actual url. 
image

**Comment by karlomikus** [comment]
Interesting, it works in testing. Can you try with the following syntax:

```env
MEILI_MASTER_KEY=
BASE_URL=http://localhost:3000
MEILISEARCH_URL=${BASE_URL}/search
API_URL=${BASE_URL}/bar
```

**Comment by MathieuMoalic** [comment]
yes that works !

**Comment by zhdenny** [comment]
Just did this big upgrade. Works beautifully now! And is much more secure now! Thank you dev!

**Pull request merged**
